import { Metadata } from "next/types";
import "./globals.css";


export const metadata: Metadata = {
  title: "Chris Bartlett",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          {children}

      </body>
    </html>
  );
}
