import FooterComponent from "@/components/footer";
import HeaderComponent from "@/components/header";
import { Metadata } from "next/types";
import "../globals.css";


export const metadata: Metadata = {
  title: "Chris Bartlett",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-barba="wrapper">
        <div className="content_container">
          <HeaderComponent />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
