import FooterComponent from "@/components/footer";
import HeaderComponent from "@/components/header";
import { Metadata } from "next/types";
import { Bebas_Neue } from "next/font/google";

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400", // Adjust weight if needed
  display: "swap",
});

import "../globals.css";


export const metadata: Metadata = {
  title: "Chris Bartlett",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={bebasNeue.className}>
      <body data-barba="wrapper">
        <div className="content_container">
          <HeaderComponent />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
